#include <Windows.h>
#ifndef VER_COMPANYNAME_STR
#define VER_COMPANYNAME_STR         "{COMPANYNAME}"
#endif
#ifndef VER_FILEDESCRIPTION_STR
#define VER_FILEDESCRIPTION_STR     "{FILEDESCRIPTION}"
#endif
#ifndef VER_INTERNALNAME_STR
#define VER_INTERNALNAME_STR        VER_FILEDESCRIPTION_STR
#endif
#ifndef VER_ORIGINALFILENAME_STR
#define VER_ORIGINALFILENAME_STR    VER_FILEDESCRIPTION_STR
#endif
#ifndef VER_PRODUCTNAME_STR
#define VER_PRODUCTNAME_STR         "{PRODUCTNAME}"
#endif
#undef VER_PRODUCTVERSION
#define VER_PRODUCTVERSION          {PRODUCTVERSION}
#undef VER_PRODUCTVERSION_STR
#define VER_PRODUCTVERSION_STR      "{PRODUCTVERSION_STR}"
#undef VER_FILEVERSION
#define VER_FILEVERSION             {FILEVERSION}
#undef VER_FILEVERSION_STR
#define VER_FILEVERSION_STR         "{FILEVERSION_STR}"
#ifndef VER_LEGALCOPYRIGHT_STR
#define VER_LEGALCOPYRIGHT_STR      "{LEGALCOPYRIGHT}"
#endif
#ifndef VER_DEBUG
#define VER_DEBUG                   VS_FF_DEBUG
#endif
